
server:
  port: 8081



spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.study.entity
  mapper-locations: classpath:/xml/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

